# Generated by Django 5.1.3 on 2026-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_profilentreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verifie',
            field=models.BooleanField(default=True),
        ),
    ]
