# Generated by Django 5.1.3 on 2026-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_codeverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletudiant',
            name='profil_public',
            field=models.BooleanField(default=True),
        ),
    ]
