# Generated by Django 5.1.3 on 2026-10-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CANDIDATURE_RECUE', 'Candidature reçue'), ('CANDIDATURE_ACCEPTEE', 'Candidature acceptée'), ('CANDIDATURE_REFUSEE', 'Candidature refusée'), ('CONVENTION_A_TRAITER', 'Convention à traiter'), ('CONVENTION_PRETE', 'Convention prête'), ('CONVENTION_SIGNEE', 'Convention signée'), ('ATTESTATION_DISPONIBLE', 'Attestation disponible')], max_length=40)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, default='', max_length=255)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation', '-id'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='notificatio_destina_d40d57_idx')],
            },
        ),
    ]
