# Generated by Django 5.1.3 on 2026-10-04 14:39

import candidatures.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to=candidatures.models.candidature_cv_path)),
                ('lettre_motivation', models.FileField(upload_to=candidatures.models.candidature_lettre_path)),
                ('message', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('commentaire_entreprise', models.TextField(blank=True, default='')),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='offres.offrestage')),
            ],
            options={
                'ordering': ['-date_candidature'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_technique', models.PositiveSmallIntegerField(help_text='Compétences techniques (sur 20)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note_autonomie', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note_communication', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note_assiduite', models.PositiveSmallIntegerField(help_text='Assiduité et ponctualité (sur 20)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('appreciation', models.TextField(blank=True, default='')),
                ('points_forts', models.TextField(blank=True, default='')),
                ('axes_amelioration', models.TextField(blank=True, default='')),
                ('recommande', models.BooleanField(default=False)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='candidatures.candidature')),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('etudiant', 'offre'), name='candidature_unique_par_offre'),
        ),
    ]
