# Generated by Django 5.1.3 on 2026-10-04 14:39

import conventions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('SIGNEE', 'Signée')], default='BROUILLON', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=conventions.models.convention_path)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='candidatures.candidature')),
            ],
        ),
    ]
