# Generated by Django 5.1.3 on 2026-10-06 08:01

import conventions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='attestation',
            field=models.FileField(blank=True, null=True, upload_to=conventions.models.attestation_path),
        ),
        migrations.AddField(
            model_name='convention',
            name='date_attestation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='fichier_signe',
            field=models.FileField(blank=True, null=True, upload_to=conventions.models.convention_signee_path),
        ),
        migrations.AddField(
            model_name='convention',
            name='lieu',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='convention',
            name='missions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='convention',
            name='motif_rejet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='convention',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='convention',
            name='sujet',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convention',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
