# Generated by Django 6.1.1 on 2026-09-16 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('domaine', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=100)),
                ('duree_mois', models.PositiveIntegerField()),
                ('competences_requises', models.TextField(help_text='Compétences séparées par des virgules (ex: Python, React, Django)')),
                ('date_limite', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('entreprise', models.ForeignKey(limit_choices_to={'role': 'ENTREPRISE'}, on_delete=django.db.models.deletion.CASCADE, related_name='offres_publier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
